@{
	DefaultCommandPrefix = "Html"
	ModuleVersion = "0.1.0"
	PowerShellVersion = "7.5"
	RootModule = "bin/Belin.Html.Cmdlets.dll"

	Author = "Cédric Belin <cedx@outlook.com>"
	CompanyName = "Cedric-Belin.fr"
	Copyright = "© Cédric Belin"
	Description = "TODO"
	GUID = "386e8ff7-f166-407e-8b42-9a5e2bac406d"

	AliasesToExport = @()
	FunctionsToExport = @()
	VariablesToExport = @()

	CmdletsToExport = @(
		"New-AElement"
		"New-AbbrElement"
		"New-AddressElement"
		"New-AreaElement"
		"New-ArticleElement"
		"New-AsideElement"
		"New-AudioElement"
		"New-BElement"
		"New-BaseElement"
		"New-BdiElement"
		"New-BdoElement"
		"New-BlockquoteElement"
		"New-BodyElement"
		"New-BrElement"
		"New-ButtonElement"
		"New-CanvasElement"
		"New-CaptionElement"
		"New-CiteElement"
		"New-CodeElement"
		"New-ColElement"
		"New-ColgroupElement"
		"New-DataElement"
		"New-DatalistElement"
		"New-DdElement"
		"New-DelElement"
		"New-DetailsElement"
		"New-DfnElement"
		"New-DialogElement"
		"New-DivElement"
		"New-DlElement"
		"New-DtElement"
		"New-EmElement"
		"New-EmbedElement"
		"New-FieldsetElement"
		"New-FigcaptionElement"
		"New-FigureElement"
		"New-FooterElement"
		"New-FormElement"
		"New-H1Element"
		"New-H2Element"
		"New-H3Element"
		"New-H4Element"
		"New-H5Element"
		"New-H6Element"
		"New-HeadElement"
		"New-HeaderElement"
		"New-HgroupElement"
		"New-HrElement"
		"New-HtmlElement"
		"New-IElement"
		"New-IframeElement"
		"New-ImgElement"
		"New-InputElement"
		"New-InsElement"
		"New-KbdElement"
		"New-LabelElement"
		"New-LegendElement"
		"New-LiElement"
		"New-LinkElement"
		"New-MainElement"
		"New-MapElement"
		"New-MarkElement"
		"New-MenuElement"
		"New-MetaElement"
		"New-MeterElement"
		"New-NavElement"
		"New-NoscriptElement"
		"New-ObjectElement"
		"New-OlElement"
		"New-OptgroupElement"
		"New-OptionElement"
		"New-OutputElement"
		"New-PElement"
		"New-PictureElement"
		"New-PreElement"
		"New-ProgressElement"
		"New-QElement"
		"New-RpElement"
		"New-RtElement"
		"New-RubyElement"
		"New-SElement"
		"New-SampElement"
		"New-ScriptElement"
		"New-SearchElement"
		"New-SectionElement"
		"New-SelectElement"
		"New-SlotElement"
		"New-SmallElement"
		"New-SourceElement"
		"New-SpanElement"
		"New-StrongElement"
		"New-StyleElement"
		"New-SubElement"
		"New-SummaryElement"
		"New-SupElement"
		"New-TableElement"
		"New-TbodyElement"
		"New-TdElement"
		"New-TemplateElement"
		"New-TextareaElement"
		"New-TfootElement"
		"New-ThElement"
		"New-TheadElement"
		"New-TimeElement"
		"New-TitleElement"
		"New-TrElement"
		"New-TrackElement"
		"New-UElement"
		"New-UlElement"
		"New-VarElement"
		"New-VideoElement"
		"New-WbrElement"
	)

	PrivateData = @{
		PSData = @{
			LicenseUri = "https://github.com/cedx/html.net/blob/main/License.md"
			ProjectUri = "https://github.com/cedx/html.net"
			ReleaseNotes = "https://github.com/cedx/html.net/releases"
			Tags = "TODO"
		}
	}
}
