@{
	ModuleVersion = "1.2.0"
	PowerShellVersion = "7.6"
	RootModule = "bin/Belin.Html.dll"

	Author = "Cédric Belin <cedx@outlook.com>"
	CompanyName = "Cedric-Belin.fr"
	Copyright = "© Cédric Belin"
	Description = "PowerShell cmdlets for rendering HTML documents."
	GUID = "3c16800c-921e-4c31-9fc3-00052d2f30ba"

	AliasesToExport = @()
	FunctionsToExport = @()
	VariablesToExport = @()

	CmdletsToExport = @(
		"New-HtmlAbbrElement"
		"New-HtmlAddressElement"
		"New-HtmlAElement"
		"New-HtmlAreaElement"
		"New-HtmlArticleElement"
		"New-HtmlAsideElement"
		"New-HtmlAudioElement"
		"New-HtmlBaseElement"
		"New-HtmlBdiElement"
		"New-HtmlBdoElement"
		"New-HtmlBElement"
		"New-HtmlBlockquoteElement"
		"New-HtmlBodyElement"
		"New-HtmlBrElement"
		"New-HtmlButtonElement"
		"New-HtmlCanvasElement"
		"New-HtmlCaptionElement"
		"New-HtmlCiteElement"
		"New-HtmlCodeElement"
		"New-HtmlColElement"
		"New-HtmlColgroupElement"
		"New-HtmlCustomElement"
		"New-HtmlDataElement"
		"New-HtmlDatalistElement"
		"New-HtmlDdElement"
		"New-HtmlDelElement"
		"New-HtmlDetailsElement"
		"New-HtmlDfnElement"
		"New-HtmlDialogElement"
		"New-HtmlDivElement"
		"New-HtmlDlElement"
		"New-HtmlDocumentType"
		"New-HtmlDtElement"
		"New-HtmlEmbedElement"
		"New-HtmlEmElement"
		"New-HtmlFieldsetElement"
		"New-HtmlFigcaptionElement"
		"New-HtmlFigureElement"
		"New-HtmlFooterElement"
		"New-HtmlFormElement"
		"New-HtmlH1Element"
		"New-HtmlH2Element"
		"New-HtmlH3Element"
		"New-HtmlH4Element"
		"New-HtmlH5Element"
		"New-HtmlH6Element"
		"New-HtmlHeadElement"
		"New-HtmlHeaderElement"
		"New-HtmlHgroupElement"
		"New-HtmlHrElement"
		"New-HtmlHtmlElement"
		"New-HtmlIElement"
		"New-HtmlIframeElement"
		"New-HtmlImgElement"
		"New-HtmlInputElement"
		"New-HtmlInsElement"
		"New-HtmlKbdElement"
		"New-HtmlLabelElement"
		"New-HtmlLegendElement"
		"New-HtmlLiElement"
		"New-HtmlLinkElement"
		"New-HtmlMainElement"
		"New-HtmlMapElement"
		"New-HtmlMarkElement"
		"New-HtmlMenuElement"
		"New-HtmlMetaElement"
		"New-HtmlMeterElement"
		"New-HtmlNavElement"
		"New-HtmlNoscriptElement"
		"New-HtmlObjectElement"
		"New-HtmlOlElement"
		"New-HtmlOptgroupElement"
		"New-HtmlOptionElement"
		"New-HtmlOutputElement"
		"New-HtmlPElement"
		"New-HtmlPictureElement"
		"New-HtmlPreElement"
		"New-HtmlProgressElement"
		"New-HtmlQElement"
		"New-HtmlRpElement"
		"New-HtmlRtElement"
		"New-HtmlRubyElement"
		"New-HtmlSampElement"
		"New-HtmlScriptElement"
		"New-HtmlSearchElement"
		"New-HtmlSectionElement"
		"New-HtmlSelectElement"
		"New-HtmlSElement"
		"New-HtmlSlotElement"
		"New-HtmlSmallElement"
		"New-HtmlSourceElement"
		"New-HtmlSpanElement"
		"New-HtmlStrongElement"
		"New-HtmlStyleElement"
		"New-HtmlSubElement"
		"New-HtmlSummaryElement"
		"New-HtmlSupElement"
		"New-HtmlTableElement"
		"New-HtmlTbodyElement"
		"New-HtmlTdElement"
		"New-HtmlTemplateElement"
		"New-HtmlTextareaElement"
		"New-HtmlTfootElement"
		"New-HtmlTheadElement"
		"New-HtmlThElement"
		"New-HtmlTimeElement"
		"New-HtmlTitleElement"
		"New-HtmlTrackElement"
		"New-HtmlTrElement"
		"New-HtmlUElement"
		"New-HtmlUlElement"
		"New-HtmlVarElement"
		"New-HtmlVideoElement"
		"New-HtmlWbrElement"
		"Out-HtmlFile"
		"Out-HtmlString"
	)

	PrivateData = @{
		PSData = @{
			LicenseUri = "https://github.com/cedx/html.net/blob/main/License.md"
			ProjectUri = "https://github.com/cedx/html.net"
			ReleaseNotes = "https://github.com/cedx/html.net/releases"
			Tags = "html", "renderer", "template", "templating", "web"
		}
	}
}
