@{
	Elements = @(
		@{ Tag = "a"; IsVoid = $false }
		@{ Tag = "abbr"; IsVoid = $false }
		@{ Tag = "address"; IsVoid = $false }
		@{ Tag = "area"; IsVoid = $true }
		@{ Tag = "article"; IsVoid = $false }
		@{ Tag = "aside"; IsVoid = $false }
		@{ Tag = "audio"; IsVoid = $false }
		@{ Tag = "b"; IsVoid = $false }
		@{ Tag = "base"; IsVoid = $true }
		@{ Tag = "bdi"; IsVoid = $false }
		@{ Tag = "bdo"; IsVoid = $false }
		@{ Tag = "blockquote"; IsVoid = $false }
		@{ Tag = "body"; IsVoid = $false }
		@{ Tag = "br"; IsVoid = $true }
		@{ Tag = "button"; IsVoid = $false }
		@{ Tag = "canvas"; IsVoid = $false }
		@{ Tag = "caption"; IsVoid = $false }
		@{ Tag = "cite"; IsVoid = $false }
		@{ Tag = "code"; IsVoid = $false }
		@{ Tag = "col"; IsVoid = $true }
		@{ Tag = "colgroup"; IsVoid = $false }
		@{ Tag = "data"; IsVoid = $false }
		@{ Tag = "datalist"; IsVoid = $false }
		@{ Tag = "dd"; IsVoid = $false }
		@{ Tag = "del"; IsVoid = $false }
		@{ Tag = "details"; IsVoid = $false }
		@{ Tag = "dfn"; IsVoid = $false }
		@{ Tag = "dialog"; IsVoid = $false }
		@{ Tag = "div"; IsVoid = $false }
		@{ Tag = "dl"; IsVoid = $false }
		@{ Tag = "dt"; IsVoid = $false }
		@{ Tag = "em"; IsVoid = $false }
		@{ Tag = "embed"; IsVoid = $true }
		@{ Tag = "fieldset"; IsVoid = $false }
		@{ Tag = "figcaption"; IsVoid = $false }
		@{ Tag = "figure"; IsVoid = $false }
		@{ Tag = "footer"; IsVoid = $false }
		@{ Tag = "form"; IsVoid = $false }
		@{ Tag = "h1"; IsVoid = $false }
		@{ Tag = "h2"; IsVoid = $false }
		@{ Tag = "h3"; IsVoid = $false }
		@{ Tag = "h4"; IsVoid = $false }
		@{ Tag = "h5"; IsVoid = $false }
		@{ Tag = "h6"; IsVoid = $false }
		@{ Tag = "head"; IsVoid = $false }
		@{ Tag = "header"; IsVoid = $false }
		@{ Tag = "hgroup"; IsVoid = $false }
		@{ Tag = "hr"; IsVoid = $true }
		@{ Tag = "html"; IsVoid = $false }
		@{ Tag = "i"; IsVoid = $false }
		@{ Tag = "iframe"; IsVoid = $false }
		@{ Tag = "img"; IsVoid = $true }
		@{ Tag = "input"; IsVoid = $true }
		@{ Tag = "ins"; IsVoid = $false }
		@{ Tag = "kbd"; IsVoid = $false }
		@{ Tag = "label"; IsVoid = $false }
		@{ Tag = "legend"; IsVoid = $false }
		@{ Tag = "li"; IsVoid = $false }
		@{ Tag = "link"; IsVoid = $true }
		@{ Tag = "main"; IsVoid = $false }
		@{ Tag = "map"; IsVoid = $false }
		@{ Tag = "mark"; IsVoid = $false }
		@{ Tag = "menu"; IsVoid = $false }
		@{ Tag = "meta"; IsVoid = $true }
		@{ Tag = "meter"; IsVoid = $false }
		@{ Tag = "nav"; IsVoid = $false }
		@{ Tag = "noscript"; IsVoid = $false }
		@{ Tag = "object"; IsVoid = $false }
		@{ Tag = "ol"; IsVoid = $false }
		@{ Tag = "optgroup"; IsVoid = $false }
		@{ Tag = "option"; IsVoid = $false }
		@{ Tag = "output"; IsVoid = $false }
		@{ Tag = "p"; IsVoid = $false }
		@{ Tag = "picture"; IsVoid = $false }
		@{ Tag = "pre"; IsVoid = $false }
		@{ Tag = "progress"; IsVoid = $false }
		@{ Tag = "q"; IsVoid = $false }
		@{ Tag = "rp"; IsVoid = $false }
		@{ Tag = "rt"; IsVoid = $false }
		@{ Tag = "ruby"; IsVoid = $false }
		@{ Tag = "s"; IsVoid = $false }
		@{ Tag = "samp"; IsVoid = $false }
		@{ Tag = "script"; IsVoid = $false }
		@{ Tag = "search"; IsVoid = $false }
		@{ Tag = "section"; IsVoid = $false }
		@{ Tag = "select"; IsVoid = $false }
		@{ Tag = "slot"; IsVoid = $false }
		@{ Tag = "small"; IsVoid = $false }
		@{ Tag = "source"; IsVoid = $true }
		@{ Tag = "span"; IsVoid = $false }
		@{ Tag = "strong"; IsVoid = $false }
		@{ Tag = "style"; IsVoid = $false }
		@{ Tag = "sub"; IsVoid = $false }
		@{ Tag = "summary"; IsVoid = $false }
		@{ Tag = "sup"; IsVoid = $false }
		@{ Tag = "table"; IsVoid = $false }
		@{ Tag = "tbody"; IsVoid = $false }
		@{ Tag = "td"; IsVoid = $false }
		@{ Tag = "template"; IsVoid = $false }
		@{ Tag = "textarea"; IsVoid = $false }
		@{ Tag = "tfoot"; IsVoid = $false }
		@{ Tag = "th"; IsVoid = $false }
		@{ Tag = "thead"; IsVoid = $false }
		@{ Tag = "time"; IsVoid = $false }
		@{ Tag = "title"; IsVoid = $false }
		@{ Tag = "tr"; IsVoid = $false }
		@{ Tag = "track"; IsVoid = $true }
		@{ Tag = "u"; IsVoid = $false }
		@{ Tag = "ul"; IsVoid = $false }
		@{ Tag = "var"; IsVoid = $false }
		@{ Tag = "video"; IsVoid = $false }
		@{ Tag = "wbr"; IsVoid = $true }
	)
}
