<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>Cedric-Belin.fr</Company>
		<Copyright>© Cédric Belin</Copyright>
		<Description>PowerShell cmdlets for rendering HTML documents.</Description>
		<Product>HTML Renderer for PowerShell</Product>
		<Version>5.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Belin.Html</AssemblyName>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Belin.Html</RootNamespace>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="$(AssemblyName).Tests" />
		<PackageReference Include="System.Management.Automation" Version="7.6.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="DataUri.fs" />
		<Compile Include="DocumentType.fs" />
		<!-- <Compile Include="Element.fs" /> -->
		<Compile Include="QueryString.fs" />
		<Compile Include="Sanitizer.fs" />
		<!-- <Compile Include="Elements/A.fs" /> -->
	</ItemGroup>
</Project>
